In [5]:
import cv2
import numpy as np


image = cv2.imread('/Users/dishanimandal/Desktop/dip/image.png')  # Replace with your image path

height, width = image.shape[:2]
resized_image = cv2.resize(image, (width // 4, height // 4))


sharpen_kernel = np.array([[ 0, -1,  0],
                           [-1,  5, -1],
                           [ 0, -1,  0]])


sharpened = cv2.filter2D(resized_image, -1, sharpen_kernel)


cv2.imshow("Original (Resized)", resized_image)
cv2.imshow("Sharpened (Resized)", sharpened)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:


arr= np.array([1,2,3,4])
print(arr)
print(type(arr))
arr2 =np.array([[1,2,3],[1,2,3]]) 
print(arr2)
filled_array= np.full((2,3),1)
arr = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
print(np.ndim(arr))
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
a = np.array([1,2,3])
print(a ** 2)
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.matmul(a,b))
a = np.array([1,2])
b = np.array([3,4])
print(np.hstack((a,b)))

[1 2 3 4]
<class 'numpy.ndarray'>
[[1 2 3]
 [1 2 3]]
3
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
[[19 22]
 [43 50]]
[1 2 3 4]


In [11]:
arr= np.arange(3,30,4)
print(arr[4:7])

[19 23 27]


In [ ]:
a=np.array([1,2,3,4,5,6])
b=a[5:7]
c= b[0]

In [2]:

cap = cv2.VideoCapture(0)
while True:
    ret, frame= cap.read()
    cv2.imshow("video",frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

error: OpenCV(4.12.0) /Users/xperience/GHA-Actions-OpenCV/_work/opencv-python/opencv-python/opencv/modules/highgui/src/window.cpp:973: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'imshow'


In [1]:
import cv2
import numpy as np
image= np.zeros((500,500,3), dtype=np.uint8)
cv2.circle(image, (256,256),100, (250,0,0),-10)
cv2.imshow("Line Image", image)
if cv2.waitKey(0)==27:
    cv2.destroyAllWindows()

        

In [1]:
import cv2
import numpy as np
image= np.zeros((512,512,3), dtype=np.uint8)
cv2.rectangle(image, (100, 200), (300,400), (0, 0, 255), 3)
cv2.imshow("Image", image)
if cv2.waitKey(0)==27:
    cv2.destroyAllWindows()


In [1]:
import cv2
import numpy as np  
import random
image= cv2.imread('boy.jpeg')
image= cv2.resize(image, (400, 400))
tiles=[img[0:200, 0:200],img[0:200, 200:400],img[200:400, 0:200],img[200:400, 200:400]] 
cv2.imshow("Cropped", cropped)
cv2.waitKey(0)
cv2.closeAllWindows()

In [5]:
import cv2 as cv
import numpy as np

img1 = cv.imread('img1.png')
img2 = cv.imread('img2.png')
print (img1.shape)

img2=cv.resize(img2,(img1.shape[1],img1.shape[0]))
result = cv.addWeighted(img1, 0.5, img2, 0.5, 1)
cv.imshow("Blended Image", result)

cv.waitKey(0)  # Keeps the image open until a key is pressed
cv.destroyAllWindows()

(1334, 1002, 3)


In [1]:
import cv2 as cv
import numpy as np

img3 = cv.imread('img3.png')
img4 = cv.imread('img4.png')
cv.imshow("Image 1", img3)
cv.imshow("Image 2", img4)
img_and= cv.bitwise_and(img3, img4)
cv.imshow("Bitwise AND", img_and)
cv.waitKey(0)  # Keeps the image open until a key is pressed
cv.destroyAllWindows()



In [1]:
import cv2 as cv
import numpy as np

img3 = cv.imread('img3.png')
img4 = cv.imread('img4.png')
cv.imshow("Image 1", img3)
cv.imshow("Image 2", img4)
img_or= cv.bitwise_or(img3, img4)
cv.imshow("Bitwise OR", img_or)
cv.waitKey(0)  # Keeps the image open until a key is pressed
cv.destroyAllWindows()



In [2]:
import cv2 as cv
import numpy as np

img3 = cv.imread('img3.png')
#img4 = cv.imread('img4.png')
cv.imshow("Image 1", img3)
#cv.imshow("Image 2", img4)
img_not= cv.bitwise_not(img3)
cv.imshow("Bitwise NOT", img_not)
cv.waitKey(0)  # Keeps the image open until a key is pressed
cv.destroyAllWindows()


In [1]:
import cv2 as cv
import numpy as np

img3 = cv.imread('img3.png')
img4 = cv.imread('img4.png')
cv.imshow("Image 1", img3)
cv.imshow("Image 2", img4)
img_xor= cv.bitwise_xor(img3, img4)
cv.imshow("Bitwise OR", img_xor)
cv.waitKey(0)  # Keeps the image open until a key is pressed
cv.destroyAllWindows()


In [1]:
import cv2
import numpy as np
img = cv2.imread('MaskImage.jpg')
cv2.imshow('Original Image', img)
HSV = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
lower_yellow = np.array([15,50,180])
upper_yellow = np.array([40,255,255])
mask = cv2.inRange(HSV, lower_yellow, upper_yellow)
cv2.imshow('Mask', mask)
result = cv2.bitwise_and(img, img, mask=mask)
cv2.imshow('masked image', result)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [1]:
import cv2 as cv
import numpy as np

img = cv.imread('rubik.jpg')
img1 = cv.imread('purple.jpg')
cv.imshow("Original Image", img)

hsv = cv.cvtColor(img, cv.COLOR_BGR2HSV)

lower_green = np.array([35, 100, 100])
upper_green = np.array([85, 255, 255])

mask = cv.inRange(hsv, lower_green, upper_green)

result = cv.bitwise_not(img, img, mask=mask)
cv.imshow("Mask", mask)
cv.imshow("Masked Image", result)


cv.waitKey(0)  # Keeps the image open until a key is pressed
cv.destroyAllWindows()

In [3]:
import cv2
img = cv2.imread('sample.png')  
img = cv2.resize(img, (500, 400)) 
def nothing(x):
    pass  # Empty function required by createTrackbar

cv2.namedWindow("Brightness Adjuster",cv2.WINDOW_NORMAL)

cv2.createTrackbar('Brightness', 'Brightness Adjuster', 50, 100, nothing)

while True:
    
    brightness = cv2.getTrackbarPos('Brightness', 'Brightness Adjuster')
    bright_img = cv2.convertScaleAbs(img, alpha=1, beta=brightness - 50)

    cv2.imshow('Brightness Adjuster', bright_img)
    if cv2.waitKey(1) & 0xFF == 27:
        break

cv2.destroyAllWindows()


In [2]:
import cv2
import numpy as np

def onChange(val):
    pass

def createTrackBar():
    cv2.namedWindow("mywindow")
    cv2.resizeWindow("mywindow", 512, 150)
    cv2.createTrackbar("red", "mywindow", 0, 255, onChange)
    cv2.createTrackbar("green", "mywindow", 0, 255, onChange)
    cv2.createTrackbar("blue", "mywindow", 0, 255, onChange)

createTrackBar()

image = np.zeros((512, 512, 3), np.uint8)

while True:
    # Get trackbar positions
    red = cv2.getTrackbarPos("red", "mywindow")
    green = cv2.getTrackbarPos("green", "mywindow")
    blue = cv2.getTrackbarPos("blue", "mywindow")

    image[:] = [blue, green, red]
    cv2.imshow("mywindow", image)

    # Exit on Esc key
    if cv2.waitKey(1) & 0xFF == 27:
        break

cv2.destroyAllWindows()

KeyboardInterrupt: 